### ISSUE TITLE
Create a Next.js app and configure the settings.

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/disaster-msg-project#1]
### Description

Create a Next.js app and configure the settings.

### Tasks

- [x] Create a Next.js app
- [x] Install Jest
- [x] Install Prettier and configure the settings
- [x] Push it to repository
- [x] Set Git commit message convention template

#### How to create Next.js + TypeScript project
```
npx create-next-app --typescript new-project
```

#### How to set Git commit message convention template
[[Git] Git 커밋 메시지 컨벤션 템플릿 설정하기](https://velog.io/@robinyoondev/Git-Git-%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80-%EC%BB%A8%EB%B2%A4%EC%85%98-%ED%85%9C%ED%94%8C%EB%A6%BF-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

#### How to use Jest
https://github.com/robinyoon-dev/typescript-project/issues/6

#### Prettier
https://dev-yakuza.posstree.com/ko/react/nextjs/prettier/

**Comment by robinyoon-dev** [comment]
# (new) How to use Jest 
https://velog.io/@robinyoondev/내가-Jest를-설치하고-사용한-방법

**Comment by robinyoon-dev** [comment]
# Git commit message convention template

```
### Git 커밋 메시지 컨벤션 ###

# ▼ <type>: <description> 작성


# ▼ obtional <body> 작성


# ▼ obtional <footer> 작성


##################
# Feat: 새로운 기능
# Fix : 버그 수정
# Docs: 문서 변경
# Style: 스타일 수정
# Refactor: 코드 리팩토링
# Test: 테스트 코드 수정
# Chore: 기타 작업
```
