### ISSUE TITLE
Use Tailwind CSS

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/disaster-msg-project#10]
### Description

https://tailwindcss.com/

### Tasks

- [x] Install Tailwind CSS
- [x] Polish message component's style by using Tailwind CSS
- [x] Document how to use Tailwind CSS

### Additional Information

- https://tailwindcss.com/docs/guides/nextjs
- https://nextjs.org/docs/app/building-your-application/styling/tailwind-css
- https://v1.tailwindcss.com/components/cards

**Comment by robinyoon-dev** [comment]
# error!
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/a104cecf-6208-4372-961a-6e5175224fcd)

## Reference
https://velog.io/@cinephile/Next.js%EC%97%90%EC%84%9C-tailwind-css-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-Unknown-at-rule-tailwind-cssunknownAtRules
