### ISSUE TITLE
일부 UX/UI 고치기

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/disaster-msg-project#17]
### Tasks

- [ ] 1. 임진강 수계지역(경기도 연천군, 파주시)와 같이 괄호 안에 있는 ', '는 분리되지 않도록 조치해보기.
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/cfb859f1-01fc-42d9-a553-8fdf81b158eb)

- [x] 2. 재난이모지가 들어가는 칸의 비율 고정하기.
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/1573baf9-4aa8-40e8-8ebd-ca8a22c6e7a3)

- [x] 3. '많은 비', '강한 비' 키워드가 들어가면 '호우'가 뜨도록 만들기.
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/a5150c12-cac2-42aa-a3a3-0a5b053a41f8)
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/fb8fa6a7-e240-4a19-aa91-1f8f29f6b2b3)

**Comment by robinyoon-dev** [comment]
# flex-basis: 아이템의 기본 크기 설정
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/21b6a7be-b097-4299-b96b-420c4f17a5ac)
![image](https://github.com/robinyoon-dev/disaster-msg-project/assets/107087958/fe63ccc9-55aa-4b3a-a12d-7e073ecf39e4)
