### ISSUE TITLE
Use Open API from data.go.kr 

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/disaster-msg-project#2]
### Description

Use Open API from data.go.kr 
https://www.data.go.kr/index.do

Data Name: 행정안전부_재난문자방송 발령현황 

### Tasks

- [x] Apply for utilization
- [ ] ⭐Write a test code
- [x] Implement the code and Ensure the code runs successfully.

### Additional Information

Reference materials 1: https://chobopark.tistory.com/190

**Comment by robinyoon-dev** [comment]
# part of `data.DisasterMsg`
```

{
  head: [
    { totalCount: 175162 },
    { numOfRows: '10', pageNo: '1', type: 'JSON' },
    { RESULT: [Object] }
  ]
}
{
  row: [
    {
      create_date: '2023/06/19 11:00:13',
      location_id: '98',
      location_name: '광주광역시 전체',
      md101_sn: '195724',
      msg: '[광주광역시청] 광주지역 폭염주의보 발효중▲한낮 야외활동을 자제▲야외근로자 무더위휴식시간제 운영하여 주시기 바랍니다.',
      send_platform: 'cbs'
    },
    {
      create_date: '2023/06/19 10:58:14',
      location_id: '186',
      location_name: '전라남도 담양군',
      md101_sn: '195723',
      msg: '[담양군청] 담양군 폭염주의보 발효중. ▲한낮 밭 작업 등 야외 활동 자제 ▲부모님 및 이웃 안부 확인 ▲충분한 물 섭취 등 안전에 유의 바랍니다.',
      send_platform: 'cbs'
    },
```
